<a href="https://colab.research.google.com/github/Risqi2112/Penelitian/blob/main/Analisis_Sentimen_PPDB_2018_2022/Pengujian_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Open data

In [1]:
! mkdir -p /root/.ssh
with open("/root/.ssh/id_rsa", mode="w") as fp:
    fp.write("""
-----BEGIN RSA PRIVATE KEY-----
MIIJKQIBAAKCAgEA28vbY5SKh6JYjsRPhz0o8m1MeY8b/RdOekzRo6zwV64wCWnU
wGy4x5UaqdkPNz5YIoTE29FY2m9Yvo9iKsgy1tcPjDvat5z+sqGfySpZgLR9HIqH
Zebyma43IqNq/oscuSsiV2SJLYsLH+cTJQUvxxSK+V1Bj8dtWrenTNh4ASGzjLVF
lY8Az6K9PtCbp4uPAzVEkKhuG1axPjTVPVxnlanIpdhewkzL8oJnn8Oy+qRMmoFC
0WqedDPZ6bhnRit1n7xk6qzguIIxb5gBW4+fFOBskoZV5i3eHReM2XEjVr/gZXGk
uUuAZfxkhv00A2RTeJXzet2SfPCTmRYiV1BBovxXhj0GVC3vO4cOgMDAlWVmEyxW
3h1rf04y4O3vfai8FXXZXCdMWA1f1MhyydrPXOvIT3MZh/NwVZCnFG9sJojWtRSj
B/xgATP1hzmznqFNY6LGsJTqHtad/9FogLdy7t6WrpUzNsQhK/rwHOkqO7WGwRIC
rd+D7FozBmF443iCMEI37uGZpRdz12Jc6ocYQ28POwxeFFAO8Y+an5cyUCkuaWBD
20hotg6JchL/tFVSoNB2gmk/SPIJt7y01opuEDsdMtja6gdl6TF5+Ge/diQXyU5w
fo9r1pKGGRrG0ehcPrw/LRZcnbYOii+G5fnqDLgc7O3j7WtWtFDYXVHHlMECAwEA
AQKCAgB5fmvc1YTliGWvNPBI7xOtPaFiKCrucW2dyMywzq1jqhM/gNJrMy3IlLDS
Zfs1LC8HlaBDaarVw2qomxVGVLdVbjdX6tXxXMSk9RYf2lry+9GUbzZ8q3Y6YMR1
TyObZEYSTLeE2zvAgvU5Qz+f3QgV4VMYl+XflfrqhE3j+lwLNBfNlX3LN+rY2zoE
eMcxi8EXouAtngyO7BK5MfcVHfjcD6erlLh8anrpqA+jjkdmqF73oK/QlkDUNr0j
phzf+rHgBAE8fycQllbBOqK1e+QRZCRfsgXVYFFAf34Jy7IfB50ANhs5mXR161ee
DmQr488H/stBhSyuB0Vu/38oCGLesBK3OeseETeXOb1jWD+KJvKvSkGf04iIET4+
x91j3O5x1c1j/l3oC4b3FUH7iSvScpEM2znP7T+UWGxEUlKM2uEweSlksAnWowgl
qQIpqKW6iE6To7MHXl6d+nOmTezCIJ2yJvBnGQMIHUXU8zYAvfqtcO6GGxK1ByPV
NB14ezMrkkJWhlv87a/8rKhhNq8g2HvdryQ6XRwn8AmMpMSeOkPXL8X7/uaQEpzP
0KbpOqwSxhHTKpcqYHcwmrR16bq1cw7lndIkCqLCdhwOXhVG7YqniRAJUXxylUMm
S6onf7EjcyrtUU0+wzmw68tcqITSgwADhQQQ8NQuCEwIcSmbgQKCAQEA/VVoBbMd
UmC/pWUbP3eS+PdcfQgnYLzjf5OupZ8aH9La4hw17MGIwE4s7IjMJwr4im68TnrE
pnXRgzdFTUfEgjPr42gZadpptQN9aKLyKa0FaCmrmcKnv5zea7Y1VtyD7fMcKPxm
h4s2P7RgDeb520HSeZK/hKDC1mVP7mIdmSZOQeuQ//uWF2eFLOnMsN2ZS2lunK2W
7N6xZydx1ThvT0u5NcAn/dUaRmaZ3rTix+JZYPXtrGGNDpl2A5SOqfDN/UA82sS3
Cvmd7XdPzb6J100BpCJYjp5R6l0o3VqTQuK3tYbTYP15mGH/WXf0U2F8vMS0QK3L
ly3vmC066yjfmQKCAQEA3hwWEhvwM7IKaIwlihWIToUkTCsufwA/G2vK8AVXhOF+
DHVhgZssZwLMDagJ3O2twjXV0qtgPuQWvnf1eS8k8ep2IJT2nkqUZP2mtFU+pPFY
PHFgJ4AWu2CHcppccH6PXc6sd1yMsmM2ck4Nm6CCp6IPzDya4q0dboprsqgafCiL
ZSfTezA31YrQN+4CGXIV2nWaKATiZ3s8TFanDJPwxfiOeXvxVMNNXGBHovPQSI6O
kYRx4bIY1TkoJGuJii+PAJeL6mLnEc0kofdZMtiCG/a9283Fbq2h7ey7nXwqOX2E
53Cl1HJ9R+M1q94uIOtHEYCRoCQR4T0rzsXXago3aQKCAQEA9nzhB5qtTvffwHfN
uUUI9cEIdoc2eUOQPxNcfL1/V7N7UUGNnlz4R9RIlaTMrrhX96mjAuEk8an1PqzK
e1T2+JC4Vb117K6c54kLvoG9CZvVhPH2i1cAjMl/CGJzJ57LpvxCTAa5Y+ypzfYc
96njNdinh66nNc6NhLlyukkw71B8GFux67/I2+DXjUm25efXPa7J9xxXmwVaqzmP
4pxUgVz2Sjw7LRjpxdISqMRrW3z65gKjTHRmIOxkDTvAS82HP3//NgTs7HrPlLvg
JBneWGQO0rqwW6PjpBscpbN5UTzy7mbOyLIYW5ION+klCvPxwGHL2JrBWslRNEnd
5+0PEQKCAQB7OgnksitqAvVTW63YFmoxZhzlRW/edjyM8hj9YXlU9+X+84DNb1IL
NLoROZF/ST6F6WhgIUScn98efV9rhIRy0yoGmZ7Z43bBMRk0I7dFu8DAiAZY4++4
ta1wH8P5hb30xZ1Z+7bzoaerczKJjVvvtTIeleE4seMKWTG3RRyslbIAxT/HsNDJ
YOJ0pU/03h7RvT1xxoP19aFWmRzFFa8Xpvck32bdKB3bim80MSD1oGHoyhqEpVKx
uaxTyHXefNRR98Jgn86jSbVxRtHuK8DD0vky4c8PwLV+U0Ej9qdWjhUWcqEOZRas
s5oraHEfQmmDhFlHB7wDwvRzG8CPzGtBAoIBAQDFtk7V82kV8UfH3S6uT59dhEqm
SD3tyMxvphtix+s4FFBJMzRSVaHZ6zGYoaDQZ2tpFz1VTlFn7tXH0kaHLjhqtbWA
0gJ6PHRbN54L0UO1Y1i0UPKCpNyaaG8dwoyP+2fKhLmrpdwIXXKBIwV4qzOT+nyI
xNsauYFduDHq3jmr3Pq3NF/xk6JFtxutk9vPB6a7sBrEFsm/Zhbuw/s2VV4R2R9o
LiK/e3Tlgk53XK4d16jlsNhvPqv8HbwTkTTg1sjYtzSBnuLQOZCTy7JPy2zr60+i
ZPFl/76wVF9oVruNH6m8y5mFNMDCKsf7Q+SQmb+QdlHGSt5M+KJam4jS2QZL
-----END RSA PRIVATE KEY-----
""")
! ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
! chmod go-rwx /root/.ssh/id_rsa
! git clone git@github.com:Risqi2112/Penelitian.git
%cd /content/Penelitian

# github.com:22 SSH-2.0-babeld-408889af
Cloning into 'Penelitian'...
remote: Enumerating objects: 477, done.
remote: Counting objects: 100% (146/146), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 477 (delta 67), reused 137 (delta 63), pack-reused 331
Receiving objects: 100% (477/477), 2.28 MiB | 2.25 MiB/s, done.
Resolving deltas: 100% (184/184), done.
/content/Penelitian


In [2]:
import pandas as pd
data = pd.read_csv('/content/Penelitian/Analisis_Sentimen_PPDB_2018_2022/Data/Hasil/Preprocessing_Tanpa_Stopword.csv',encoding='utf-8',error_bad_lines=False)
data.head(), data.shape

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)


(  sentimen  tahun                                              tweet
 0   Netral   2018  informasi ppdb menghubungi telepon hunting ext...
 1   Netral   2018  ppdb sdn daerah khusus ibukota jakarta sertaka...
 2   Netral   2018            informasi ppdb sds regina pacis jakarta
 3   Netral   2018  ppdb smk telekomunikasi jakarta penerimaan pes...
 4   Netral   2018  ombudsman perwakilan jakarta raya menemukan du...,
 (273, 3))

In [3]:
data.sentimen.replace(['Negatif','Netral','Positif'],[-1,0,1],inplace=True)
data.head()

sentimen  tahun                                              tweet
0         0   2018  informasi ppdb menghubungi telepon hunting ext...
1         0   2018  ppdb sdn daerah khusus ibukota jakarta sertaka...
2         0   2018            informasi ppdb sds regina pacis jakarta
3         0   2018  ppdb smk telekomunikasi jakarta penerimaan pes...
4         0   2018  ombudsman perwakilan jakarta raya menemukan du...

In [4]:
# Pembagian train_data & test_data
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.model_selection import train_test_split
import pickle
import pandas as pd

seed = 99
testSize = 0.2

x_train, x_test, y_train, y_test = train_test_split(data["tweet"], data["sentimen"], 
                                                    test_size=testSize, random_state = seed)
x_train = x_train.values.astype('U')
x_test = x_test.values.astype('U')
y_train = y_train.values.astype('U')
y_test = y_test.values.astype('U')

print(x_train.shape, x_test.shape)

(218,) (55,)


In [5]:
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.pipeline import make_pipeline
from sklearn import svm

In [6]:
# Optimasi Hyperparameter/temukan parameter terbaik menggunakan gridCV
try:
  optSvm = pickle.load(open('Model_optimal_2', 'rb'))
except:
  kCV = 5
  metric = 'accuracy'
  params = {}
  params['tfidfvectorizer__min_df'] = [1, 2, 5, 10, 30]
  params['tfidfvectorizer__max_df'] = [0.5, 0.75, 0.9, 0.95, 1.0]
  params['tfidfvectorizer__smooth_idf'] = [True, False]
  params['tfidfvectorizer__sublinear_tf'] = [True, False]
  params['tfidfvectorizer__ngram_range'] = [(1, 1), (1, 2), (1,3)]
  params['svc__C'] = [1, 5, 10] #sp.stats.uniform(scale=100)
  params['svc__gamma'] = [0.1, 1, 10]
  params['svc__kernel'] = ['rbf', 'sigmoid', 'linear', 'poly']
  params['svc__decision_function_shape'] = ['ovo', 'ovr']
  pipe = make_pipeline(TfidfVectorizer(), svm.SVC())
  optSvm = GridSearchCV(pipe, params, cv=kCV, scoring=metric, verbose=0, n_jobs=-2) # refit=True, pre_dispatch='2*n_jobs' pre_dispatch min 2* n_jobs
  optSvm.fit(x_train, y_train)
  pickle.dump(optSvm, open('Model_optimal_2', 'wb'))

print(optSvm.best_score_)
print(optSvm.best_params_)

0.7798097251585623
{'svc__C': 5, 'svc__decision_function_shape': 'ovo', 'svc__gamma': 1, 'svc__kernel': 'rbf', 'tfidfvectorizer__max_df': 0.5, 'tfidfvectorizer__min_df': 1, 'tfidfvectorizer__ngram_range': (1, 1), 'tfidfvectorizer__smooth_idf': False, 'tfidfvectorizer__sublinear_tf': True}


In [7]:
#Tf-idf
vsm = TfidfVectorizer(lowercase=True, smooth_idf= False, sublinear_tf=True, 
                                   ngram_range=(1, 1), max_df=0.5, min_df=1)
x_train = vsm.fit_transform(x_train) # "Fit_Transform"
x_test = vsm.transform(x_test) # Perhatikan disini hanya "Transform"

print(x_train.shape, x_test.shape) # Jumlah kolom Sama ==> ini penting

(218, 980) (55, 980)


In [8]:
corpus_ = set(vsm.vocabulary_)

In [9]:
# Algoritma SVM menggunakan parameter optimal
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, classification_report

dSVM = svm.SVC(C=5,decision_function_shape='ovo',gamma=1,kernel='rbf')
dSVM.fit(x_train, y_train)
y_SVM = dSVM.predict(x_test)

# Evaluasi
print('Akurasi = ', accuracy_score(y_test, y_SVM))
print(confusion_matrix(y_test, y_SVM))
print(classification_report(y_test, y_SVM))

Akurasi =  0.8
[[12  2  1]
 [ 2 14  2]
 [ 2  2 18]]
              precision    recall  f1-score   support

          -1       0.75      0.80      0.77        15
           0       0.78      0.78      0.78        18
           1       0.86      0.82      0.84        22

    accuracy                           0.80        55
   macro avg       0.79      0.80      0.80        55
weighted avg       0.80      0.80      0.80        55



In [10]:

Data_predict = pd.read_csv('/content/Penelitian/Analisis_Sentimen_PPDB_2018_2022/Data/Hasil/Data_prediksi.csv',encoding='utf-8',error_bad_lines=False)
Data_predict.head(), Data_predict.shape

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)


(   tahun                                              tweet
 0   2018  pendaftaran pengumuman hasil seleksi ppdb onli...
 1   2018  come and join us ppdb smk telekomunikasi jakar...
 2   2018  informasi pendaftaran ppdb smk telekomunikasi ...
 3   2018  radar bogor catat rekomendasi ombudsman pelaks...
 4   2018   hii doain keterima ppdb sman jakarta amin semoga, (8181, 2))

In [11]:
xpred = Data_predict['tweet']
xpred=xpred.values.astype('U')

In [12]:
minLength = 3
data = ()
for dt in xpred:
  tokens_ = dt.split()
  L = len([1 for k in tokens_ if k in corpus_])
  if L>= minLength:
    data.append(dt)
print("Jumlah Data terfilter = {}".format(len(data)))
data()

Jumlah Data terfilter = 6759


['pendaftaran pengumuman hasil seleksi ppdb online smk daerah khusus ibukota jakarta',
 'come and join us ppdb smk telekomunikasi jakarta smk telekomunikasi jakarta sekolah keren menerapkan budaya redi ccp character content process berbasis gitu olah raga',
 'informasi pendaftaran ppdb smk telekomunikasi jakarta ta keterangan silahkan hubungi petugas ppdb nomor nomor prosedur pendaftaran akses manual',
 'radar bogor catat rekomendasi ombudsman pelaksanaan ppdb jakarta radar bogor',
 'hii doain keterima ppdb sman jakarta amin semoga',
 'radar bogor sistem zonasi ppdb pemerataan pendidikan jakarta radar bogor anggapan sek',
 'ombudsman ri hasil pemantauan ppdb sekretaris jenderal pejabat kantor ombudsman jakarta']

In [13]:
#from sklearn.feature_extraction.text import TfidfVectorizer
#vsm = TfidfVectorizer(lowercase=True, smooth_idf= False, sublinear_tf=True, 
#                                   ngram_range=(1, 1), max_df=0.5, min_df=1)

pred = vsm.transform(data)

In [17]:
hasil_prediksi = optSvm.predict(pred)

AttributeError: ignored